import './globals.css'
import './scrollbar.css'
import "./typography.css"
import "@fortawesome/fontawesome-svg-core/styles.css"
import {config} from   "@fortawesome/fontawesome-svg-core"
import { Inter } from 'next/font/google'

config.autoAddCss = false

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Chioma Okeke',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
